### PR TITLE
[travis] Use Bionic distribution

### PR DESCRIPTION
**Pull request by strk**
Let's get modern!

### CODE REVIEW

**Comment by strk** [comment]
I'm afraid Travis just silently ignores the `bionic` request, because packages are still being fetched from `xenial` !

Documentation does not mentio Bionic at all: https://docs.travis-ci.com/user/reference/overview/

**Comment by imincik** [comment]
> I'm afraid Travis just silently ignores the bionic request, because packages are still being fetched from xenial !

@strk , this is what we are talking about whole time when we are complaining about Travis CI.

**Comment by imincik** [comment]
But for example, this build is using Bionic - https://travis-ci.org/linz/postgresql-tableversion/jobs/550688563#L6

**Comment by strk** [comment]
> But for example, this build is using Bionic - https://travis-ci.org/linz/postgresql-tableversion/jobs/550688563#L6

I'm not sure, because the `apt-get update` call is made quiet so we
don't know which packages is really downloading (Bionic was advertised
also in other builds, but the `apt-get update` call revealed packages
were being fetched for Xenial instead).

**Pull request merged**
